#!/bin/sh
# Regenerate fixtures_test.mbt from fixtures/ok/*.json and fixtures/bad/*.json.
#
# MoonBit tests do not read files at runtime (keeps tests portable across all
# backends), so every fixture is embedded verbatim as a `#|` multiline string.
#
# Usage:
#   scripts/gen_fixture_tests.sh          # rewrite fixtures_test.mbt
#   scripts/gen_fixture_tests.sh --check  # exit 1 if fixtures_test.mbt is stale
set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT="$ROOT/fixtures_test.mbt"
MANIFEST="$ROOT/fixtures/bad/expected.txt"
export LC_ALL=C

emit_text() {
  # $1 = file; prints its lines as `  let text =` + `    #|...` lines
  echo "  let text ="
  while IFS= read -r line || [ -n "$line" ]; do
    if [ -z "$line" ]; then
      echo "    #|"
    else
      echo "    #|$line"
    fi
  done <"$1"
}

expected_code() {
  # $1 = basename; prints expected code from manifest or nothing
  awk -v f="$1" '$0 !~ /^#/ && $1 == f { print $2; exit }' "$MANIFEST"
}

generate() {
  echo "// Code generated by scripts/gen_fixture_tests.sh; DO NOT EDIT."
  echo "// Regenerate after changing fixtures/: scripts/gen_fixture_tests.sh"
  echo
  echo "///|"
  echo "fn fixture_has_code("
  echo "  diags : Array[@agent-schema-lint.Diagnostic],"
  echo "  code : String,"
  echo ") -> Bool {"
  echo "  for d in diags {"
  echo "    if d.code == code && d.severity == @agent-schema-lint.Error {"
  echo "      return true"
  echo "    }"
  echo "  }"
  echo "  false"
  echo "}"
  for f in "$ROOT"/fixtures/ok/*.json; do
    name=$(basename "$f")
    echo
    echo "///|"
    echo "test \"fixture ok/$name has no errors\" {"
    emit_text "$f"
    echo "  let diags = @agent-schema-lint.lint(text)"
    echo "  assert_false(@agent-schema-lint.has_errors(diags))"
    echo "}"
  done
  for f in "$ROOT"/fixtures/bad/*.json; do
    name=$(basename "$f")
    code=$(expected_code "$name")
    if [ -z "$code" ]; then
      echo "error: fixtures/bad/$name has no entry in fixtures/bad/expected.txt" >&2
      exit 1
    fi
    echo
    echo "///|"
    echo "test \"fixture bad/$name reports $code\" {"
    emit_text "$f"
    echo "  let diags = @agent-schema-lint.lint(text)"
    echo "  assert_true(@agent-schema-lint.has_errors(diags))"
    echo "  assert_true(fixture_has_code(diags, \"$code\"))"
    echo "}"
  done
}

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT
generate >"$TMP"

if [ "${1:-}" = "--check" ]; then
  if cmp -s "$TMP" "$OUT"; then
    echo "fixtures_test.mbt is up to date"
  else
    echo "fixtures_test.mbt is stale; run scripts/gen_fixture_tests.sh" >&2
    exit 1
  fi
else
  cp "$TMP" "$OUT"
  echo "wrote $OUT"
fi
